### ISSUE TITLE
Add torus axis of revolution as a runtime parameter

### ISSUE THREAD

**Issue by 56th** [56th/drops#4]
Add parameter "Surface.Params.Torus.Axis" to json and to [torus ctor](https://github.com/56th/drops/blob/32b7182d4fe13be52c676ecfd32f08ab5b8e3333/src/surfactant/Surface.hpp#L72). Right now axis is "fixed" to z, i.e. level-set/dist func depends on (x, y).

We need the following:
"Surface.Params.Torus.Axis" = 0 -> phi = phi(x[1], x[2])
"Surface.Params.Torus.Axis" = 1 -> phi = phi(x[0], x[2])
"Surface.Params.Torus.Axis" = 2 -> phi = phi(x[0], x[1])

Will be useful for Rayleigh-Taylor instability test and maybe in the future.

**Comment by palzhanov** [comment]
Added as follows:
When axis of revolution is 
- x, then r[xi] will change along y-axis
- y, then r[xi] will change along z-axis
- z, then r[xi] will change along x-axis

**Comment by 56th** [comment]
63e9290eafc9a333f76a458ca354ca848d16d605
6e5d1eb4f93a64fa32e191fef9976b2c49ed74f5
